version: '3.8'
services:
  gateway:
    build: ./gateway/
    image: 11-alpine-jdk
    container_name: gateway_docker
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server/
    image: 11-alpine-jdk
    container_name: server_docker
    ports:
      - "9090:9090"
    depends_on:
      - db



  db:
    image: postgres:13.7-alpine
    container_name: db_docker
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


